[build]
builder = "Nixpacks"
buildCommand = "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate"

[start]
startCommand = "gunicorn insightboard_backend.wsgi --chdir backend"